gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Iono_WelcomeToArceusCup::
	.string "Ladies aaand gentlemens!\p"
	.string "It's time for the Iono Zone!\n"
	.string "I'm Iono a Gym Leader from the\l"
	.string "Paldea League, broadcasting live..\p"
	.string "The Arceus Cup! Champions from around\n"
	.string "the World has gathered to prove that\l"
	.string "they are the very best.\p"

	.string "I do agree that they are the very best.\p"
	.string "Hello everyone, I am Professor Oak, a\n"
	.string "researcher from the Kanto Region, here\l"
	.string "to give you the indept analysis, while\l"
	.string "Lady Iono here will give the colorful\l"
	.string "commentary.\p"

	.string "Together we will be your hosts across\n"
	.string "the events and at this very moment-\p"
	.string "The Arceus Cup...\p"
	.string "Officialy Starting!!!\n"
	.string "See you there everyone and good luck\l"
	.string "to our contestants! Show them who's-\p"
	.string "THE VERY BEST!\n"
	.string "$" 
